sudo: false
language: node_js
node_js:
  - "5.3"
cache:
  directories:
    - node_modules
env:
 - CXX=g++-4.8
addons:
 apt:
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - gcc-4.8
    - g++-4.8
install: travis_retry npm install
script:
  - node --harmony node_modules/polyserve/bin/polyserve & node node_modules/gemini/bin/gemini test visual-test/test.js
